version: '3.4'

services:
  everythingburrito:
    image: everythingburrito
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

networks:
  burritonet:
    driver: bridge
