version: '3.4'

services:
  app:
    image: everything-burrito
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - burrito-net
  redis:
    image: redis:latest
    networks:
      - burrito-net

networks:
  burrito-net:
    driver: bridge
